# Generated by Django 5.2.4 on 2026-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('feature', models.CharField(max_length=40)),
                ('response_text', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'copilot_response_cache',
            },
        ),
        migrations.CreateModel(
            name='CopilotTenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('daily_token_budget', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'copilot_tenant_config',
            },
        ),
        migrations.CreateModel(
            name='CopilotEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('source_table', models.CharField(max_length=100)),
                ('source_pk', models.IntegerField()),
                ('content', models.TextField()),
                ('vector', models.JSONField()),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'copilot_embedding',
                'indexes': [models.Index(fields=['tenant_id', 'source_table'], name='copilot_emb_tenant__f67557_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_table', 'source_pk'), name='copilot_embedding_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='CopilotUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('feature', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('prompt_redacted', models.TextField(blank=True)),
                ('response_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'copilot_usage_log',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='copilot_usa_tenant__699878_idx')],
            },
        ),
    ]
