import os
import sys
import tempfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "helpdesk_project.settings")
os.environ["DJANGO_DB_PATH"] = os.path.join(tempfile.gettempdir(), "copilot_cost_table.sqlite3")

import django  # noqa: E402

django.setup()

from django.conf import settings  # noqa: E402
from django.core.management import call_command  # noqa: E402

from copilot.models import CopilotResponseCache, CopilotUsageLog  # noqa: E402
from copilot.services import ask_data  # noqa: E402
from copilot.services.pricing import cost_usd  # noqa: E402
from tests.support import make_fake  # noqa: E402

QUESTIONS = [
    "How many open tickets are there?",
    "List the high priority tickets",
    "Which customers are on the pro plan?",
]
REPEATS = 100


def _reset_db():
    if os.path.exists(os.environ["DJANGO_DB_PATH"]):
        os.remove(os.environ["DJANGO_DB_PATH"])
    call_command("migrate", verbosity=0)
    from helpdesk.seeding import seed

    return seed()["acme"].id


def _totals():
    logs = CopilotUsageLog.objects.all()
    input_tokens = sum(log.input_tokens for log in logs)
    output_tokens = sum(log.output_tokens for log in logs)
    model_calls = logs.filter(cache_hit=False).count()
    return input_tokens, output_tokens, model_calls


def _run_scenario(tenant_id, clear_cache_each_request):
    CopilotUsageLog.objects.all().delete()
    CopilotResponseCache.objects.all().delete()
    fake = make_fake()
    requests = 0
    for _ in range(REPEATS):
        for question in QUESTIONS:
            if clear_cache_each_request:
                CopilotResponseCache.objects.all().delete()
            ask_data.run_ask(tenant_id, question, llm=fake)
            requests += 1
    input_tokens, output_tokens, model_calls = _totals()
    total_cost = cost_usd(input_tokens, output_tokens)
    return {
        "requests": requests,
        "model_calls": model_calls,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_cost_usd": total_cost,
        "cost_per_1k": total_cost / requests * 1000,
    }


def _row(label, scenario):
    return (
        f"| {label} | {scenario['requests']} | {scenario['model_calls']} | "
        f"{scenario['input_tokens']} | {scenario['output_tokens']} | "
        f"${scenario['total_cost_usd']:.4f} | ${scenario['cost_per_1k']:.4f} |"
    )


def main():
    tenant_id = _reset_db()
    settings.COPILOT["DAILY_TOKEN_BUDGET"] = 10_000_000
    uncached = _run_scenario(tenant_id, clear_cache_each_request=True)
    cached = _run_scenario(tenant_id, clear_cache_each_request=False)
    reduction = (1 - cached["cost_per_1k"] / uncached["cost_per_1k"]) * 100

    price_in = settings.COPILOT["PRICE_INPUT_PER_MTOK"]
    price_out = settings.COPILOT["PRICE_OUTPUT_PER_MTOK"]

    lines = [
        "# Ask-your-data cost: before vs after caching",
        "",
        "Generated by `scripts/generate_cost_table.py`. Every number below is produced by",
        "running the ask-your-data pipeline against the offline recorded provider responses",
        f"in `copilot/llm/recorded_demo.json`, so the run is fully reproducible. Prices are the",
        f"configured list rates (${price_in:.2f} / MTok input, ${price_out:.2f} / MTok output for",
        "`claude-haiku-4-5`); token counts are the recorded input/output tokens per call.",
        "",
        f"Workload: {len(QUESTIONS)} distinct questions issued {REPEATS} times each",
        f"({uncached['requests']} requests). Each ask makes two model calls (SQL generation +",
        "answer). These are recorded-fixture figures, not live traffic. Set",
        "`COPILOT_LLM_BACKEND=anthropic` and run against real questions for measured production numbers.",
        "",
        "| Scenario | Requests | Model calls | Input tokens | Output tokens | Total cost | Cost / 1k requests |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        _row("No caching", uncached),
        _row("With response cache", cached),
        "",
        f"**Caching cut cost per 1k requests by {reduction:.1f}%** on this repeat-heavy workload",
        f"(from ${uncached['cost_per_1k']:.4f} to ${cached['cost_per_1k']:.4f} per 1k), because",
        "identical redacted questions are served from `copilot_response_cache` instead of the model.",
        "The savings scale with the repeat rate of your real traffic.",
        "",
    ]
    with open(os.path.join(os.path.dirname(__file__), "..", "docs", "COST-TABLE.md"), "w") as handle:
        handle.write("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
